# Generated by Django 3.1 on 2021-01-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='one_click_purchasing',
            field=models.BooleanField(default=False),
        ),
    ]
