# Generated by Django 3.1 on 2021-01-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_one_click_purchasing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
    ]
