# Generated by Django 3.1 on 2021-01-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
