# Generated by Django 3.1 on 2021-01-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
